name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verificar se a pasta src existe
        run: |
          if [ ! -d src ]; then
            echo "ERRO: pasta src nao encontrada!"
            exit 1
          fi

      - name: Verificar se o CSS está no caminho correto
        run: |
          if [ ! -f src/css/style.css ]; then
            echo "ERRO: arquivo src/css/style.css nao encontrado!"
            exit 1
          fi

      - name: Verificar se existe footer com o nome do aluno
        run: |
          if ! grep -qi "<footer>.*david.*</footer>" src/index.html; then
          echo "ERRO: O arquivo src/index.html não contém um <footer> com o nome do aluno!"
          exit 1
          fi
      # ————— HTMLHint —————
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install HTMLHint
        run: npm install -g htmlhint

      - name: Lint HTML
        run: htmlhint "src/index.html"

      - name: Explorando o Runner
        run: lsb_release -a && free -h

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'src'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Auditoria Final
        run: echo "O código do aluno DAVID foi auditado, está seguindo as normas corretas e está pronto para o deploy!"
